# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.milestone_bulk_action import MilestoneBulkAction

class TestMilestoneBulkAction(unittest.TestCase):
    """MilestoneBulkAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneBulkAction:
        """Test MilestoneBulkAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneBulkAction`
        """
        model = MilestoneBulkAction()
        if include_optional:
            return MilestoneBulkAction(
                resource = airfocus_client.models.update_milestone_request.UpdateMilestoneRequest(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    name = '', 
                    timezone = '', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ]
            )
        else:
            return MilestoneBulkAction(
                resource = airfocus_client.models.update_milestone_request.UpdateMilestoneRequest(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    name = '', 
                    timezone = '', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ],
        )
        """

    def testMilestoneBulkAction(self):
        """Test MilestoneBulkAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
