# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_apply_template(self) -> None:
        """Test case for apply_template

        Install template
        """
        pass

    def test_apply_template_legacy(self) -> None:
        """Test case for apply_template_legacy

        Install template
        """
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List templates
        """
        pass

    def test_list_templates_legacy(self) -> None:
        """Test case for list_templates_legacy

        List templates
        """
        pass


if __name__ == '__main__':
    unittest.main()
