# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.global_search_api import GlobalSearchApi


class TestGlobalSearchApi(unittest.TestCase):
    """GlobalSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GlobalSearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_global(self) -> None:
        """Test case for search_global

        """
        pass


if __name__ == '__main__':
    unittest.main()
