# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.team_flags import TeamFlags

class TestTeamFlags(unittest.TestCase):
    """TeamFlags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamFlags:
        """Test TeamFlags
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamFlags`
        """
        model = TeamFlags()
        if include_optional:
            return TeamFlags(
                enable_ai = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                enable_okr_app = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                forbid_share_link_creation = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                remove_branding = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_portal_login = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_portal_password = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_share_link_password = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                restrict_share_link_creation = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, )
            )
        else:
            return TeamFlags(
                enable_ai = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                enable_okr_app = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                forbid_share_link_creation = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                remove_branding = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_portal_login = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_portal_password = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                require_share_link_password = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
                restrict_share_link_creation = airfocus_client.models.team_flag.TeamFlag(
                    enforced = True, 
                    explicit = True, 
                    value = True, ),
        )
        """

    def testTeamFlags(self):
        """Test TeamFlags"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
