# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.items_relations_api import ItemsRelationsApi


class TestItemsRelationsApi(unittest.TestCase):
    """ItemsRelationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsRelationsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_item_relations(self) -> None:
        """Test case for bulk_item_relations

        Perform multiple operations with item-relations
        """
        pass

    def test_create_item_relation(self) -> None:
        """Test case for create_item_relation

        Create a new item-relation
        """
        pass

    def test_delete_item_relation(self) -> None:
        """Test case for delete_item_relation

        Delete an existing item-relation
        """
        pass

    def test_list_item_relations(self) -> None:
        """Test case for list_item_relations

        Retrieve multiple item-relations by their IDs
        """
        pass

    def test_patch_item_relation(self) -> None:
        """Test case for patch_item_relation

        Patch an existing item-relation
        """
        pass

    def test_retrieve_item_relation(self) -> None:
        """Test case for retrieve_item_relation

        Retrieve a single item-relation by its ID
        """
        pass

    def test_search_item_relations(self) -> None:
        """Test case for search_item_relations

        Retrieve or search item-relations
        """
        pass

    def test_update_item_relation(self) -> None:
        """Test case for update_item_relation

        Update an existing item-relation
        """
        pass


if __name__ == '__main__':
    unittest.main()
