# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.workspace_permissions_update_request import WorkspacePermissionsUpdateRequest

class TestWorkspacePermissionsUpdateRequest(unittest.TestCase):
    """WorkspacePermissionsUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspacePermissionsUpdateRequest:
        """Test WorkspacePermissionsUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspacePermissionsUpdateRequest`
        """
        model = WorkspacePermissionsUpdateRequest()
        if include_optional:
            return WorkspacePermissionsUpdateRequest(
                permissions = {
                    'key' : 'comment'
                    },
                default_permission = 'comment'
            )
        else:
            return WorkspacePermissionsUpdateRequest(
                permissions = {
                    'key' : 'comment'
                    },
        )
        """

    def testWorkspacePermissionsUpdateRequest(self):
        """Test WorkspacePermissionsUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
