# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.team import Team

class TestTeam(unittest.TestCase):
    """Team unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Team:
        """Test Team
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Team`
        """
        model = Team()
        if include_optional:
            return Team(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                flags = airfocus_client.models.team_flags.TeamFlags(
                    enable_ai = airfocus_client.models.team_flag.TeamFlag(
                        enforced = True, 
                        explicit = True, 
                        value = True, ), 
                    enable_okr_app = airfocus_client.models.team_flag.TeamFlag(
                        enforced = True, 
                        explicit = True, 
                        value = True, ), 
                    forbid_share_link_creation = , 
                    remove_branding = , 
                    require_portal_login = , 
                    require_portal_password = , 
                    require_share_link_password = , 
                    restrict_share_link_creation = , ),
                name = '',
                slug = '',
                state = airfocus_client.models.team_state.TeamState(
                    features = [
                        ''
                        ], 
                    seats = airfocus_client.models.team_state_all_team_state_seats.TeamStateAllTeamStateSeats(
                        admin = airfocus_client.models.team_state_seats.TeamStateSeats(
                            free = 56, 
                            total = 56, 
                            used = 56, ), 
                        any = airfocus_client.models.team_state_seats.TeamStateSeats(
                            free = 56, 
                            total = 56, 
                            used = 56, ), 
                        contributor = , 
                        editor = , ), 
                    subscription = null, 
                    trial_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    workspaces = airfocus_client.models.team_state_workspaces.TeamStateWorkspaces(
                        total = 56, ), ),
                team_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                company_info = airfocus_client.models.team_company_info.TeamCompanyInfo(
                    role = 'customerSuccess', 
                    size = 'range1000plus', 
                    telephone = '', )
            )
        else:
            return Team(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                flags = airfocus_client.models.team_flags.TeamFlags(
                    enable_ai = airfocus_client.models.team_flag.TeamFlag(
                        enforced = True, 
                        explicit = True, 
                        value = True, ), 
                    enable_okr_app = airfocus_client.models.team_flag.TeamFlag(
                        enforced = True, 
                        explicit = True, 
                        value = True, ), 
                    forbid_share_link_creation = , 
                    remove_branding = , 
                    require_portal_login = , 
                    require_portal_password = , 
                    require_share_link_password = , 
                    restrict_share_link_creation = , ),
                name = '',
                slug = '',
                state = airfocus_client.models.team_state.TeamState(
                    features = [
                        ''
                        ], 
                    seats = airfocus_client.models.team_state_all_team_state_seats.TeamStateAllTeamStateSeats(
                        admin = airfocus_client.models.team_state_seats.TeamStateSeats(
                            free = 56, 
                            total = 56, 
                            used = 56, ), 
                        any = airfocus_client.models.team_state_seats.TeamStateSeats(
                            free = 56, 
                            total = 56, 
                            used = 56, ), 
                        contributor = , 
                        editor = , ), 
                    subscription = null, 
                    trial_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    workspaces = airfocus_client.models.team_state_workspaces.TeamStateWorkspaces(
                        total = 56, ), ),
                team_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTeam(self):
        """Test Team"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
