# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.workspace_bulk_action import WorkspaceBulkAction

class TestWorkspaceBulkAction(unittest.TestCase):
    """WorkspaceBulkAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceBulkAction:
        """Test WorkspaceBulkAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceBulkAction`
        """
        model = WorkspaceBulkAction()
        if include_optional:
            return WorkspaceBulkAction(
                resource = airfocus_client.models.update_workspace_request.UpdateWorkspaceRequest(
                    alias = '', 
                    default_permission = 'comment', 
                    description = airfocus_client.models.rich_text.RichText(
                        blocks = [
                            null
                            ], ), 
                    item_color = 'amber', 
                    item_type = 'bug', 
                    name = '', 
                    order = 56, 
                    progress_mode = 'count', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ]
            )
        else:
            return WorkspaceBulkAction(
                resource = airfocus_client.models.update_workspace_request.UpdateWorkspaceRequest(
                    alias = '', 
                    default_permission = 'comment', 
                    description = airfocus_client.models.rich_text.RichText(
                        blocks = [
                            null
                            ], ), 
                    item_color = 'amber', 
                    item_type = 'bug', 
                    name = '', 
                    order = 56, 
                    progress_mode = 'count', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ],
        )
        """

    def testWorkspaceBulkAction(self):
        """Test WorkspaceBulkAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
