# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.update_item_request import UpdateItemRequest

class TestUpdateItemRequest(unittest.TestCase):
    """UpdateItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateItemRequest:
        """Test UpdateItemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateItemRequest`
        """
        model = UpdateItemRequest()
        if include_optional:
            return UpdateItemRequest(
                color = 'amber',
                description = airfocus_client.models.rich_text.RichText(
                    blocks = [
                        null
                        ], ),
                fields = {
                    'key' : null
                    },
                name = '',
                order = 56,
                status_id = '',
                archived = True,
                assignee_user_ids = [
                    ''
                    ]
            )
        else:
            return UpdateItemRequest(
                color = 'amber',
                description = airfocus_client.models.rich_text.RichText(
                    blocks = [
                        null
                        ], ),
                fields = {
                    'key' : null
                    },
                name = '',
                order = 56,
                status_id = '',
        )
        """

    def testUpdateItemRequest(self):
        """Test UpdateItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
