# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.team_company_info_role import TeamCompanyInfoRole

class TestTeamCompanyInfoRole(unittest.TestCase):
    """TeamCompanyInfoRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamCompanyInfoRole(self):
        """Test TeamCompanyInfoRole"""
        # inst = TeamCompanyInfoRole()

if __name__ == '__main__':
    unittest.main()
