# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.create_milestone_request import CreateMilestoneRequest

class TestCreateMilestoneRequest(unittest.TestCase):
    """CreateMilestoneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMilestoneRequest:
        """Test CreateMilestoneRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMilestoneRequest`
        """
        model = CreateMilestoneRequest()
        if include_optional:
            return CreateMilestoneRequest(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                description = '',
                name = '',
                timezone = ''
            )
        else:
            return CreateMilestoneRequest(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                description = '',
                name = '',
        )
        """

    def testCreateMilestoneRequest(self):
        """Test CreateMilestoneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
