# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.create_item_link_request import CreateItemLinkRequest

class TestCreateItemLinkRequest(unittest.TestCase):
    """CreateItemLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateItemLinkRequest:
        """Test CreateItemLinkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateItemLinkRequest`
        """
        model = CreateItemLinkRequest()
        if include_optional:
            return CreateItemLinkRequest(
                from_item_id = '',
                from_order = 56,
                to_item_id = '',
                to_order = 56,
                type = 'dependency'
            )
        else:
            return CreateItemLinkRequest(
                from_item_id = '',
                from_order = 56,
                to_item_id = '',
                to_order = 56,
                type = 'dependency',
        )
        """

    def testCreateItemLinkRequest(self):
        """Test CreateItemLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
