# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.field_server_endpoints_reconfigure_field_request_settings import FieldServerEndpointsReconfigureFieldRequestSettings

class TestFieldServerEndpointsReconfigureFieldRequestSettings(unittest.TestCase):
    """FieldServerEndpointsReconfigureFieldRequestSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldServerEndpointsReconfigureFieldRequestSettings:
        """Test FieldServerEndpointsReconfigureFieldRequestSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldServerEndpointsReconfigureFieldRequestSettings`
        """
        model = FieldServerEndpointsReconfigureFieldRequestSettings()
        if include_optional:
            return FieldServerEndpointsReconfigureFieldRequestSettings(
                overflow = True,
                low = 56,
                medium = 56,
                auto_assign = True,
                multi = True,
                maximum = 1.337,
                minimum = 1.337,
                stepping = None,
                unit = None,
                time_periods = [
                    airfocus_client.models.time_period.TimePeriod(
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        id = '', 
                        label = '', 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                options = [
                    airfocus_client.models.select_field_type_option.SelectFieldTypeOption(
                        color = 'blue', 
                        default = True, 
                        description = '', 
                        id = '', 
                        name = '', 
                        numeric_value = 1.337, )
                    ]
            )
        else:
            return FieldServerEndpointsReconfigureFieldRequestSettings(
                overflow = True,
                low = 56,
                medium = 56,
                auto_assign = True,
                multi = True,
        )
        """

    def testFieldServerEndpointsReconfigureFieldRequestSettings(self):
        """Test FieldServerEndpointsReconfigureFieldRequestSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
