# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airfocus_client.models.workspace_group_with_workspace_group_search_embed import WorkspaceGroupWithWorkspaceGroupSearchEmbed

class TestWorkspaceGroupWithWorkspaceGroupSearchEmbed(unittest.TestCase):
    """WorkspaceGroupWithWorkspaceGroupSearchEmbed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGroupWithWorkspaceGroupSearchEmbed:
        """Test WorkspaceGroupWithWorkspaceGroupSearchEmbed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGroupWithWorkspaceGroupSearchEmbed`
        """
        model = WorkspaceGroupWithWorkspaceGroupSearchEmbed()
        if include_optional:
            return WorkspaceGroupWithWorkspaceGroupSearchEmbed(
                embedded = airfocus_client.models.workspace_group_search_embed.WorkspaceGroupSearchEmbed(
                    current_permission = 'comment', 
                    permissions = {
                        'key' : 'comment'
                        }, 
                    workspace_ids = [
                        ''
                        ], 
                    workspaces = [
                        airfocus_client.models.workspace.Workspace(
                            alias = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            default_permission = 'comment', 
                            description = airfocus_client.models.rich_text.RichText(
                                blocks = [
                                    null
                                    ], ), 
                            id = '', 
                            item_color = 'amber', 
                            item_type = 'bug', 
                            last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            metadata = airfocus_client.models.workspace_workspace_metadata.WorkspaceWorkspaceMetadata(
                                duplicated = True, 
                                template_id = '', 
                                template_workspace_ref = '', 
                                version = '', ), 
                            name = '', 
                            namespace = 'main', 
                            order = 56, 
                            progress_mode = 'count', 
                            team_id = '', )
                        ], ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                order = 56,
                team_id = '',
                default_permission = 'comment',
                parent_id = ''
            )
        else:
            return WorkspaceGroupWithWorkspaceGroupSearchEmbed(
                embedded = airfocus_client.models.workspace_group_search_embed.WorkspaceGroupSearchEmbed(
                    current_permission = 'comment', 
                    permissions = {
                        'key' : 'comment'
                        }, 
                    workspace_ids = [
                        ''
                        ], 
                    workspaces = [
                        airfocus_client.models.workspace.Workspace(
                            alias = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            default_permission = 'comment', 
                            description = airfocus_client.models.rich_text.RichText(
                                blocks = [
                                    null
                                    ], ), 
                            id = '', 
                            item_color = 'amber', 
                            item_type = 'bug', 
                            last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            metadata = airfocus_client.models.workspace_workspace_metadata.WorkspaceWorkspaceMetadata(
                                duplicated = True, 
                                template_id = '', 
                                template_workspace_ref = '', 
                                version = '', ), 
                            name = '', 
                            namespace = 'main', 
                            order = 56, 
                            progress_mode = 'count', 
                            team_id = '', )
                        ], ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                order = 56,
                team_id = '',
        )
        """

    def testWorkspaceGroupWithWorkspaceGroupSearchEmbed(self):
        """Test WorkspaceGroupWithWorkspaceGroupSearchEmbed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
