# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_workspaces(self) -> None:
        """Test case for bulk_workspaces

        Perform multiple operations with workspaces
        """
        pass

    def test_count_workspaces(self) -> None:
        """Test case for count_workspaces

        Count workspaces in the current team.
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a new workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete an existing workspace
        """
        pass

    def test_duplicate_workspace(self) -> None:
        """Test case for duplicate_workspace

        Duplicate workspace with all its items and apps.
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        Retrieve multiple workspaces by their IDs
        """
        pass

    def test_patch_workspace(self) -> None:
        """Test case for patch_workspace

        Patch an existing workspace
        """
        pass

    def test_retrieve_workspace(self) -> None:
        """Test case for retrieve_workspace

        Retrieve a single workspace by its ID
        """
        pass

    def test_search_workspaces(self) -> None:
        """Test case for search_workspaces

        Retrieve or search workspaces
        """
        pass

    def test_set_workspace_statuses(self) -> None:
        """Test case for set_workspace_statuses

        Configure workspace statuses.
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update an existing workspace
        """
        pass

    def test_update_workspace_permissions(self) -> None:
        """Test case for update_workspace_permissions

        Update workspace permissions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
