# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from airfocus_client.models.item_link_type import ItemLinkType
from typing import Optional, Set
from typing_extensions import Self

class UpdateItemLinkRequest(BaseModel):
    """
    UpdateItemLinkRequest
    """ # noqa: E501
    from_item_id: StrictStr = Field(alias="fromItemId")
    from_order: StrictInt = Field(description="How this item-link is ordered in the list of links of the \"fromItem\".", alias="fromOrder")
    to_item_id: StrictStr = Field(alias="toItemId")
    to_order: StrictInt = Field(description="How this item-link is ordered in the list of links of the \"toItem\".", alias="toOrder")
    type: ItemLinkType
    __properties: ClassVar[List[str]] = ["fromItemId", "fromOrder", "toItemId", "toOrder", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateItemLinkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateItemLinkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fromItemId": obj.get("fromItemId"),
            "fromOrder": obj.get("fromOrder"),
            "toItemId": obj.get("toItemId"),
            "toOrder": obj.get("toOrder"),
            "type": obj.get("type")
        })
        return _obj


