# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from airfocus_client.models.permission import Permission
from typing import Optional, Set
from typing_extensions import Self

class WorkspaceGroup(BaseModel):
    """
    An entity for grouping workspaces (like folders).
    """ # noqa: E501
    created_at: datetime = Field(description="Date-time when this group was created.", alias="createdAt")
    id: StrictStr = Field(description="UUID of this group.")
    last_updated_at: datetime = Field(description="Date-time when this group was last updated.", alias="lastUpdatedAt")
    name: StrictStr = Field(description="Name of this group.")
    order: StrictInt = Field(description="Order number of this group for sorting.")
    team_id: StrictStr = Field(description="UUID of the team which owns this group.", alias="teamId")
    default_permission: Optional[Permission] = Field(default=None, description="Default permission for all team-members to all the inner contents of this group.", alias="defaultPermission")
    parent_id: Optional[StrictStr] = Field(default=None, description="UUID of the parent group (if applicable).", alias="parentId")
    __properties: ClassVar[List[str]] = ["createdAt", "id", "lastUpdatedAt", "name", "order", "teamId", "defaultPermission", "parentId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "lastUpdatedAt": obj.get("lastUpdatedAt"),
            "name": obj.get("name"),
            "order": obj.get("order"),
            "teamId": obj.get("teamId"),
            "defaultPermission": obj.get("defaultPermission"),
            "parentId": obj.get("parentId")
        })
        return _obj


