# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from airfocus_client.models.item_color import ItemColor
from airfocus_client.models.item_type import ItemType
from airfocus_client.models.permission import Permission
from airfocus_client.models.rich_text import RichText
from airfocus_client.models.workspace_namespace import WorkspaceNamespace
from airfocus_client.models.workspace_progress_mode import WorkspaceProgressMode
from airfocus_client.models.workspace_workspace_metadata import WorkspaceWorkspaceMetadata
from typing import Optional, Set
from typing_extensions import Self

class Workspace(BaseModel):
    """
    Workspace
    """ # noqa: E501
    created_at: datetime = Field(description="Timestamp of when this workspace was created.", alias="createdAt")
    description: RichText = Field(description="Description of this workspace.")
    id: StrictStr = Field(description="Unique identifier of this workspace.")
    last_updated_at: datetime = Field(description="Timestamp of when this workspace was last updated.", alias="lastUpdatedAt")
    name: StrictStr = Field(description="Name of this workspace.")
    namespace: WorkspaceNamespace = Field(description="The system namespace of this workspace.")
    order: StrictInt = Field(description="Order number of this workspace for sorting.")
    progress_mode: WorkspaceProgressMode = Field(alias="progressMode")
    team_id: StrictStr = Field(description="Id of the team this workspace belongs to.", alias="teamId")
    alias: Optional[StrictStr] = Field(default=None, description="A custom code of this workspace (e.g. PROD, DEV, etc), which is used to create aliases for items (e.g. DEV-123). Alias should consist of 1-10 uppercase letters, and should be unique within the team.")
    default_permission: Optional[Permission] = Field(default=None, description="Default permission for all the team members in this workspace. Note: the final permission can be adjusted corresponding to each user's role, e.g. contributors can't have more than Comment permission.", alias="defaultPermission")
    item_color: Optional[ItemColor] = Field(default=None, description="Default color applied to newly created items in this workspace. If not defined - a random color will be assigned to each new item.", alias="itemColor")
    item_type: Optional[ItemType] = Field(default=None, description="Type of items in this workspace.", alias="itemType")
    metadata: Optional[WorkspaceWorkspaceMetadata] = None
    __properties: ClassVar[List[str]] = ["createdAt", "description", "id", "lastUpdatedAt", "name", "namespace", "order", "progressMode", "teamId", "alias", "defaultPermission", "itemColor", "itemType", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Workspace from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict['description'] = self.description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Workspace from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "description": RichText.from_dict(obj["description"]) if obj.get("description") is not None else None,
            "id": obj.get("id"),
            "lastUpdatedAt": obj.get("lastUpdatedAt"),
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "order": obj.get("order"),
            "progressMode": obj.get("progressMode"),
            "teamId": obj.get("teamId"),
            "alias": obj.get("alias"),
            "defaultPermission": obj.get("defaultPermission"),
            "itemColor": obj.get("itemColor"),
            "itemType": obj.get("itemType"),
            "metadata": WorkspaceWorkspaceMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None
        })
        return _obj


