# coding: utf-8

# flake8: noqa

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.37.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CRUDApi",
    "CommentsApi",
    "FieldsApi",
    "GlobalSearchApi",
    "ItemAttachmentsApi",
    "ItemsApi",
    "ItemsLinksApi",
    "ItemsRelationsApi",
    "MilestonesApi",
    "ProfileApi",
    "TeamApi",
    "TemplatesApi",
    "WorkspaceGroupsApi",
    "WorkspaceRelationsApi",
    "WorkspacesApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiKey",
    "App",
    "ApplyTemplateRequest",
    "AttachmentSearchQuery",
    "BooleanFieldWithFieldEmbed",
    "BulkInviteUsersRequest",
    "BulkInviteUsersRequestUser",
    "ChangePasswordRequest",
    "ChangeUserDisabledRequest",
    "ChangeUserRoleRequest",
    "CommentBulkAction",
    "CommentBulkCreate",
    "CommentBulkDelete",
    "CommentBulkPatch",
    "CommentBulkUpdate",
    "CreateApiKeyRequest",
    "CreateApiKeyResponse",
    "CreateItemLinkRequest",
    "CreateItemRequest",
    "CreateItemRequestWithMD",
    "CreateMilestoneRequest",
    "CreateUserInviteRequest",
    "CreateWorkspaceRequest",
    "DateFieldWithFieldEmbed",
    "DateRangeFieldWithFieldEmbed",
    "Emoji",
    "ErrorResponse",
    "FieldEmbed",
    "FieldFieldWorkspaceEmbed",
    "FieldSearchQuery",
    "FieldServerEndpointsFieldToWorkspaceLink",
    "FieldServerEndpointsFieldTypeInfo",
    "FieldServerEndpointsInstallFieldRequest",
    "FieldServerEndpointsInstallFieldRequestLegacy",
    "FieldServerEndpointsReconfigureFieldRequest",
    "FieldServerEndpointsReconfigureFieldRequestLegacy",
    "FieldServerEndpointsReconfigureFieldRequestSettings",
    "FieldServerEndpointsReorderFieldsRequest",
    "FieldServerEndpointsUninstallFieldRequest",
    "FieldWithFieldEmbed",
    "FieldWithFieldEmbedPage",
    "FormSourceFieldTypeSettings",
    "FormSourceFieldWithFieldEmbed",
    "FormTargetFieldWithFieldEmbed",
    "GlobalSearchQuery",
    "GlobalSearchResultItem",
    "GlobalSearchResultPage",
    "InboxViewCounter",
    "InboxViewCountersRequest",
    "InsightsFieldTypeSettings",
    "InsightsFieldWithFieldEmbed",
    "InstallBooleanFieldRequest",
    "InstallDateFieldRequest",
    "InstallDateRangeFieldRequest",
    "InstallNumberFieldRequest",
    "InstallPeopleFieldRequest",
    "InstallSelectFieldRequest",
    "InstallTextFieldRequest",
    "InstallTimePeriodFieldRequest",
    "IntegrationCapabilities",
    "IntegrationSummary",
    "IntegrationSyncState",
    "InviteUserRequest",
    "Item",
    "ItemAttachment",
    "ItemAttachmentBulkAction",
    "ItemAttachmentBulkCreate",
    "ItemAttachmentBulkDelete",
    "ItemAttachmentBulkPatch",
    "ItemAttachmentBulkUpdate",
    "ItemAttachmentWithEmbed",
    "ItemAttachmentWithEmbedPage",
    "ItemBulkAction",
    "ItemBulkCreate",
    "ItemBulkDelete",
    "ItemBulkPatch",
    "ItemBulkUpdate",
    "ItemColor",
    "ItemComment",
    "ItemCommentReaction",
    "ItemCommentSearchQuery",
    "ItemCommentWithItemCommentEmbed",
    "ItemCommentWithItemCommentEmbedPage",
    "ItemConstraint",
    "ItemConstraintIntegrationPushForbidden",
    "ItemConstraintIntegrationToInternal",
    "ItemConstraintPropertyReadOnly",
    "ItemConstraintUndeletable",
    "ItemEmbed",
    "ItemEmbedApp",
    "ItemEmbedIntegration",
    "ItemEmbedProgress",
    "ItemLinkBulkAction",
    "ItemLinkBulkCreate",
    "ItemLinkBulkDelete",
    "ItemLinkBulkPatch",
    "ItemLinkBulkUpdate",
    "ItemLinkConstraintUndeletable",
    "ItemLinkEmbed",
    "ItemLinkEmbedApp",
    "ItemLinkSearchQuery",
    "ItemLinkType",
    "ItemLinkWithItemLinkEmbed",
    "ItemLinkWithItemLinkEmbedPage",
    "ItemRelationBulkAction",
    "ItemRelationBulkCreate",
    "ItemRelationBulkDelete",
    "ItemRelationBulkPatch",
    "ItemRelationBulkUpdate",
    "ItemRelationCreateRequest",
    "ItemRelationSearchQuery",
    "ItemRelationSearchQueryFilter",
    "ItemRelationSearchQueryFilterChild",
    "ItemRelationSearchQueryFilterParent",
    "ItemRelationSearchQueryFilterParentOrChild",
    "ItemRelationUpdateRequest",
    "ItemRelationWithEmbed",
    "ItemRelationWithEmbedPage",
    "ItemSearchQuery",
    "ItemSearchQueryDateTimeFilterValue",
    "ItemSearchQueryFilter",
    "ItemSearchQueryFilterAnd",
    "ItemSearchQueryFilterAssignees",
    "ItemSearchQueryFilterAssigneesContain",
    "ItemSearchQueryFilterAssigneesContainsAll",
    "ItemSearchQueryFilterAssigneesContainsAny",
    "ItemSearchQueryFilterCreatedAt",
    "ItemSearchQueryFilterFieldValue",
    "ItemSearchQueryFilterIntegration",
    "ItemSearchQueryFilterIntegrationValue",
    "ItemSearchQueryFilterLastUpdatedAt",
    "ItemSearchQueryFilterName",
    "ItemSearchQueryFilterNameContain",
    "ItemSearchQueryFilterNameEqual",
    "ItemSearchQueryFilterNot",
    "ItemSearchQueryFilterOr",
    "ItemSearchQueryFilterParent",
    "ItemSearchQueryFilterParentValue",
    "ItemSearchQueryFilterStatus",
    "ItemSearchQueryFilterStatusCategory",
    "ItemSearchQueryFilterStatusCategoryContainsAny",
    "ItemSearchQueryFilterStatusCategoryUpdatedSince",
    "ItemSearchQueryFilterStatusContainsAny",
    "ItemSearchQueryFilterStatusUpdatedSince",
    "ItemSearchQueryFilterUpdatedSince",
    "ItemSearchQuerySort",
    "ItemSearchQuerySortCreatedAt",
    "ItemSearchQuerySortDirection",
    "ItemSearchQuerySortField",
    "ItemSearchQuerySortLastUpdatedAt",
    "ItemSearchQuerySortName",
    "ItemSearchQuerySortOrder",
    "ItemSearchQuerySortStatus",
    "ItemSearchQueryTimeAnchor",
    "ItemSearchQueryTimeAnchorDays",
    "ItemSearchQueryTimeAnchorMonths",
    "ItemSearchQueryTimeAnchorWeeks",
    "ItemSearchQueryTimeMode",
    "ItemType",
    "ItemWithItemEmbed",
    "ItemWithItemEmbedPage",
    "ItemWithMDWithItemEmbed",
    "ItemWithMDWithItemEmbedPage",
    "JsonPatchAdd",
    "JsonPatchCopy",
    "JsonPatchMove",
    "JsonPatchOperation",
    "JsonPatchRemove",
    "JsonPatchReplace",
    "JsonPatchTest",
    "KickUserRequest",
    "MilestoneBulkAction",
    "MilestoneBulkCreate",
    "MilestoneBulkDelete",
    "MilestoneBulkPatch",
    "MilestoneBulkUpdate",
    "MilestoneWithEmbed",
    "MilestoneWithEmbedPage",
    "MirrorSourceFieldWithFieldEmbed",
    "MirrorTargetFieldWithFieldEmbed",
    "NumberFieldTypeSettings",
    "NumberFieldTypeSettingsStepping",
    "NumberFieldTypeSettingsSteppingEqual",
    "NumberFieldTypeSettingsSteppingExponential",
    "NumberFieldTypeSettingsUnit",
    "NumberFieldTypeSettingsUnitCustom",
    "NumberFieldTypeSettingsUnitMoney",
    "NumberFieldWithFieldEmbed",
    "OkrCheckinsFieldWithFieldEmbed",
    "OkrConfidenceFieldSettings",
    "OkrConfidenceFieldWithFieldEmbed",
    "OkrKeyResultReferenceFieldWithFieldEmbed",
    "OkrKeyResultsFieldWithFieldEmbed",
    "OkrProgressFieldWithFieldEmbed",
    "OkrTimePeriodFieldSettings",
    "OkrTimePeriodFieldWithFieldEmbed",
    "PeopleFieldTypeSettings",
    "PeopleFieldWithFieldEmbed",
    "Permission",
    "PortalFieldWithFieldEmbed",
    "PrioritizationFieldWithFieldEmbed",
    "RefItemProperty",
    "RelativeItemInfo",
    "ResendUserInviteRequest",
    "RichText",
    "RichTextBlock",
    "RichTextBlockAttachment",
    "RichTextBlockBlockquote",
    "RichTextBlockCode",
    "RichTextBlockCustom",
    "RichTextBlockEmbed",
    "RichTextBlockHeadline",
    "RichTextBlockIndentation",
    "RichTextBlockList",
    "RichTextBlockPanel",
    "RichTextBlockParagraph",
    "RichTextInline",
    "RichTextInlineBold",
    "RichTextInlineCode",
    "RichTextInlineCustom",
    "RichTextInlineImage",
    "RichTextInlineItalic",
    "RichTextInlineLink",
    "RichTextInlineMention",
    "RichTextInlineStrikeThrough",
    "RichTextInlineText",
    "RichTextInlineUnderline",
    "RichTextListItem",
    "Role",
    "SelectFieldOptionColor",
    "SelectFieldTypeOption",
    "SelectFieldTypeSettings",
    "SelectFieldWithFieldEmbed",
    "SetClientSettingsRequest",
    "SetWorkspaceStatusesRequest",
    "Status",
    "StatusCategory",
    "StatusColor",
    "StoreAcceptedTosRequest",
    "Team",
    "TeamCompanyInfo",
    "TeamCompanyInfoRole",
    "TeamCompanyInfoSize",
    "TeamFlag",
    "TeamFlags",
    "TeamState",
    "TeamStateAllTeamStateSeats",
    "TeamStateSeats",
    "TeamStateSubscription",
    "TeamStateSubscriptionExpired",
    "TeamStateSubscriptionTrial",
    "TeamStateWorkspaces",
    "Template",
    "TemplateApp",
    "TemplateCategory",
    "TemplatePageWithEmbed",
    "TemplateParameters",
    "TemplateSearchEmbed",
    "TemplateView",
    "TextFieldWithFieldEmbed",
    "TimePeriod",
    "TimePeriodFieldSettings",
    "TimePeriodFieldSettingsIterations",
    "TimePeriodFieldSettingsSimple",
    "TimePeriodFieldWithFieldEmbed",
    "UpdateItemLinkRequest",
    "UpdateItemRequest",
    "UpdateItemRequestWithMD",
    "UpdateMilestoneRequest",
    "UpdateTeamFlagsRequest",
    "UpdateUserRequest",
    "UpdateWorkspaceRequest",
    "User",
    "UserRef",
    "UserRefUserRefId",
    "UserState",
    "View",
    "VotesFieldWithFieldEmbed",
    "VotingAppScoreFieldTypeSettings",
    "VotingScoreFieldWithFieldEmbed",
    "Workspace",
    "WorkspaceBulkAction",
    "WorkspaceBulkCreate",
    "WorkspaceBulkDelete",
    "WorkspaceBulkPatch",
    "WorkspaceBulkUpdate",
    "WorkspaceDuplicateRequest",
    "WorkspaceEmbed",
    "WorkspaceEmbedRelation",
    "WorkspaceEmbedWorkspaceGroup",
    "WorkspaceGroup",
    "WorkspaceGroupAssignWorkspaceRequest",
    "WorkspaceGroupBulkAction",
    "WorkspaceGroupBulkCreate",
    "WorkspaceGroupBulkDelete",
    "WorkspaceGroupBulkPatch",
    "WorkspaceGroupBulkUpdate",
    "WorkspaceGroupEmbed",
    "WorkspaceGroupPermissionsUpdateRequest",
    "WorkspaceGroupSearchEmbed",
    "WorkspaceGroupWithWorkspaceGroupEmbed",
    "WorkspaceGroupWithWorkspaceGroupSearchEmbed",
    "WorkspaceGroupWithWorkspaceGroupSearchEmbedPage",
    "WorkspaceNamespace",
    "WorkspacePermissionsUpdateRequest",
    "WorkspaceProgressMode",
    "WorkspaceRelation",
    "WorkspaceRelationBulkAction",
    "WorkspaceRelationBulkCreate",
    "WorkspaceRelationBulkDelete",
    "WorkspaceRelationBulkPatch",
    "WorkspaceRelationBulkUpdate",
    "WorkspaceRelationSearchQuery",
    "WorkspaceRelationSearchQueryFilter",
    "WorkspaceRelationSearchQueryFilterAnd",
    "WorkspaceRelationSearchQueryFilterChild",
    "WorkspaceRelationSearchQueryFilterChildContainAny",
    "WorkspaceRelationSearchQueryFilterChildEqual",
    "WorkspaceRelationSearchQueryFilterNot",
    "WorkspaceRelationSearchQueryFilterOr",
    "WorkspaceRelationSearchQueryFilterParent",
    "WorkspaceRelationSearchQueryFilterParentContainAny",
    "WorkspaceRelationSearchQueryFilterParentEqual",
    "WorkspaceRelationWithEmbed",
    "WorkspaceRelationWithEmbedPage",
    "WorkspaceRelationsSetRequest",
    "WorkspaceSearchEmbed",
    "WorkspaceSearchQuery",
    "WorkspaceSearchQueryFilter",
    "WorkspaceSearchQueryFilterAnd",
    "WorkspaceSearchQueryFilterMembersContainAny",
    "WorkspaceSearchQueryFilterName",
    "WorkspaceSearchQueryFilterNameContain",
    "WorkspaceSearchQueryFilterNameEqual",
    "WorkspaceSearchQueryFilterNamespaceContainAny",
    "WorkspaceSearchQueryFilterNot",
    "WorkspaceSearchQueryFilterOr",
    "WorkspaceSearchQuerySort",
    "WorkspaceSearchQuerySortCreatedAt",
    "WorkspaceSearchQuerySortDirection",
    "WorkspaceSearchQuerySortLastUpdatedAt",
    "WorkspaceSearchQuerySortName",
    "WorkspaceWithWorkspaceEmbed",
    "WorkspaceWithWorkspaceSearchEmbed",
    "WorkspaceWithWorkspaceSearchEmbedPage",
    "WorkspaceWorkspaceMetadata",
]

# import apis into sdk package
from api.crud_api import CRUDApi as CRUDApi
from api.comments_api import CommentsApi as CommentsApi
from api.fields_api import FieldsApi as FieldsApi
from api.global_search_api import GlobalSearchApi as GlobalSearchApi
from api.item_attachments_api import ItemAttachmentsApi as ItemAttachmentsApi
from api.items_api import ItemsApi as ItemsApi
from api.items_links_api import ItemsLinksApi as ItemsLinksApi
from api.items_relations_api import ItemsRelationsApi as ItemsRelationsApi
from api.milestones_api import MilestonesApi as MilestonesApi
from api.profile_api import ProfileApi as ProfileApi
from api.team_api import TeamApi as TeamApi
from api.templates_api import TemplatesApi as TemplatesApi
from api.workspace_groups_api import WorkspaceGroupsApi as WorkspaceGroupsApi
from api.workspace_relations_api import WorkspaceRelationsApi as WorkspaceRelationsApi
from api.workspaces_api import WorkspacesApi as WorkspacesApi
from api.default_api import DefaultApi as DefaultApi

# import ApiClient
from airfocus_client.api_response import ApiResponse as ApiResponse
from airfocus_client.api_client import ApiClient as ApiClient
from airfocus_client.configuration import Configuration as Configuration
from airfocus_client.exceptions import OpenApiException as OpenApiException
from airfocus_client.exceptions import ApiTypeError as ApiTypeError
from airfocus_client.exceptions import ApiValueError as ApiValueError
from airfocus_client.exceptions import ApiKeyError as ApiKeyError
from airfocus_client.exceptions import ApiAttributeError as ApiAttributeError
from airfocus_client.exceptions import ApiException as ApiException

# import models into sdk package
from airfocus_client.models.api_key import ApiKey as ApiKey
from airfocus_client.models.app import App as App
from airfocus_client.models.apply_template_request import ApplyTemplateRequest as ApplyTemplateRequest
from airfocus_client.models.attachment_search_query import AttachmentSearchQuery as AttachmentSearchQuery
from airfocus_client.models.boolean_field_with_field_embed import BooleanFieldWithFieldEmbed as BooleanFieldWithFieldEmbed
from airfocus_client.models.bulk_invite_users_request import BulkInviteUsersRequest as BulkInviteUsersRequest
from airfocus_client.models.bulk_invite_users_request_user import BulkInviteUsersRequestUser as BulkInviteUsersRequestUser
from airfocus_client.models.change_password_request import ChangePasswordRequest as ChangePasswordRequest
from airfocus_client.models.change_user_disabled_request import ChangeUserDisabledRequest as ChangeUserDisabledRequest
from airfocus_client.models.change_user_role_request import ChangeUserRoleRequest as ChangeUserRoleRequest
from airfocus_client.models.comment_bulk_action import CommentBulkAction as CommentBulkAction
from airfocus_client.models.comment_bulk_create import CommentBulkCreate as CommentBulkCreate
from airfocus_client.models.comment_bulk_delete import CommentBulkDelete as CommentBulkDelete
from airfocus_client.models.comment_bulk_patch import CommentBulkPatch as CommentBulkPatch
from airfocus_client.models.comment_bulk_update import CommentBulkUpdate as CommentBulkUpdate
from airfocus_client.models.create_api_key_request import CreateApiKeyRequest as CreateApiKeyRequest
from airfocus_client.models.create_api_key_response import CreateApiKeyResponse as CreateApiKeyResponse
from airfocus_client.models.create_item_link_request import CreateItemLinkRequest as CreateItemLinkRequest
from airfocus_client.models.create_item_request import CreateItemRequest as CreateItemRequest
from airfocus_client.models.create_item_request_with_md import CreateItemRequestWithMD as CreateItemRequestWithMD
from airfocus_client.models.create_milestone_request import CreateMilestoneRequest as CreateMilestoneRequest
from airfocus_client.models.create_user_invite_request import CreateUserInviteRequest as CreateUserInviteRequest
from airfocus_client.models.create_workspace_request import CreateWorkspaceRequest as CreateWorkspaceRequest
from airfocus_client.models.date_field_with_field_embed import DateFieldWithFieldEmbed as DateFieldWithFieldEmbed
from airfocus_client.models.date_range_field_with_field_embed import DateRangeFieldWithFieldEmbed as DateRangeFieldWithFieldEmbed
from airfocus_client.models.emoji import Emoji as Emoji
from airfocus_client.models.error_response import ErrorResponse as ErrorResponse
from airfocus_client.models.field_embed import FieldEmbed as FieldEmbed
from airfocus_client.models.field_field_workspace_embed import FieldFieldWorkspaceEmbed as FieldFieldWorkspaceEmbed
from airfocus_client.models.field_search_query import FieldSearchQuery as FieldSearchQuery
from airfocus_client.models.field_server_endpoints_field_to_workspace_link import FieldServerEndpointsFieldToWorkspaceLink as FieldServerEndpointsFieldToWorkspaceLink
from airfocus_client.models.field_server_endpoints_field_type_info import FieldServerEndpointsFieldTypeInfo as FieldServerEndpointsFieldTypeInfo
from airfocus_client.models.field_server_endpoints_install_field_request import FieldServerEndpointsInstallFieldRequest as FieldServerEndpointsInstallFieldRequest
from airfocus_client.models.field_server_endpoints_install_field_request_legacy import FieldServerEndpointsInstallFieldRequestLegacy as FieldServerEndpointsInstallFieldRequestLegacy
from airfocus_client.models.field_server_endpoints_reconfigure_field_request import FieldServerEndpointsReconfigureFieldRequest as FieldServerEndpointsReconfigureFieldRequest
from airfocus_client.models.field_server_endpoints_reconfigure_field_request_legacy import FieldServerEndpointsReconfigureFieldRequestLegacy as FieldServerEndpointsReconfigureFieldRequestLegacy
from airfocus_client.models.field_server_endpoints_reconfigure_field_request_settings import FieldServerEndpointsReconfigureFieldRequestSettings as FieldServerEndpointsReconfigureFieldRequestSettings
from airfocus_client.models.field_server_endpoints_reorder_fields_request import FieldServerEndpointsReorderFieldsRequest as FieldServerEndpointsReorderFieldsRequest
from airfocus_client.models.field_server_endpoints_uninstall_field_request import FieldServerEndpointsUninstallFieldRequest as FieldServerEndpointsUninstallFieldRequest
from airfocus_client.models.field_with_field_embed import FieldWithFieldEmbed as FieldWithFieldEmbed
from airfocus_client.models.field_with_field_embed_page import FieldWithFieldEmbedPage as FieldWithFieldEmbedPage
from airfocus_client.models.form_source_field_type_settings import FormSourceFieldTypeSettings as FormSourceFieldTypeSettings
from airfocus_client.models.form_source_field_with_field_embed import FormSourceFieldWithFieldEmbed as FormSourceFieldWithFieldEmbed
from airfocus_client.models.form_target_field_with_field_embed import FormTargetFieldWithFieldEmbed as FormTargetFieldWithFieldEmbed
from airfocus_client.models.global_search_query import GlobalSearchQuery as GlobalSearchQuery
from airfocus_client.models.global_search_result_item import GlobalSearchResultItem as GlobalSearchResultItem
from airfocus_client.models.global_search_result_page import GlobalSearchResultPage as GlobalSearchResultPage
from airfocus_client.models.inbox_view_counter import InboxViewCounter as InboxViewCounter
from airfocus_client.models.inbox_view_counters_request import InboxViewCountersRequest as InboxViewCountersRequest
from airfocus_client.models.insights_field_type_settings import InsightsFieldTypeSettings as InsightsFieldTypeSettings
from airfocus_client.models.insights_field_with_field_embed import InsightsFieldWithFieldEmbed as InsightsFieldWithFieldEmbed
from airfocus_client.models.install_boolean_field_request import InstallBooleanFieldRequest as InstallBooleanFieldRequest
from airfocus_client.models.install_date_field_request import InstallDateFieldRequest as InstallDateFieldRequest
from airfocus_client.models.install_date_range_field_request import InstallDateRangeFieldRequest as InstallDateRangeFieldRequest
from airfocus_client.models.install_number_field_request import InstallNumberFieldRequest as InstallNumberFieldRequest
from airfocus_client.models.install_people_field_request import InstallPeopleFieldRequest as InstallPeopleFieldRequest
from airfocus_client.models.install_select_field_request import InstallSelectFieldRequest as InstallSelectFieldRequest
from airfocus_client.models.install_text_field_request import InstallTextFieldRequest as InstallTextFieldRequest
from airfocus_client.models.install_time_period_field_request import InstallTimePeriodFieldRequest as InstallTimePeriodFieldRequest
from airfocus_client.models.integration_capabilities import IntegrationCapabilities as IntegrationCapabilities
from airfocus_client.models.integration_summary import IntegrationSummary as IntegrationSummary
from airfocus_client.models.integration_sync_state import IntegrationSyncState as IntegrationSyncState
from airfocus_client.models.invite_user_request import InviteUserRequest as InviteUserRequest
from airfocus_client.models.item import Item as Item
from airfocus_client.models.item_attachment import ItemAttachment as ItemAttachment
from airfocus_client.models.item_attachment_bulk_action import ItemAttachmentBulkAction as ItemAttachmentBulkAction
from airfocus_client.models.item_attachment_bulk_create import ItemAttachmentBulkCreate as ItemAttachmentBulkCreate
from airfocus_client.models.item_attachment_bulk_delete import ItemAttachmentBulkDelete as ItemAttachmentBulkDelete
from airfocus_client.models.item_attachment_bulk_patch import ItemAttachmentBulkPatch as ItemAttachmentBulkPatch
from airfocus_client.models.item_attachment_bulk_update import ItemAttachmentBulkUpdate as ItemAttachmentBulkUpdate
from airfocus_client.models.item_attachment_with_embed import ItemAttachmentWithEmbed as ItemAttachmentWithEmbed
from airfocus_client.models.item_attachment_with_embed_page import ItemAttachmentWithEmbedPage as ItemAttachmentWithEmbedPage
from airfocus_client.models.item_bulk_action import ItemBulkAction as ItemBulkAction
from airfocus_client.models.item_bulk_create import ItemBulkCreate as ItemBulkCreate
from airfocus_client.models.item_bulk_delete import ItemBulkDelete as ItemBulkDelete
from airfocus_client.models.item_bulk_patch import ItemBulkPatch as ItemBulkPatch
from airfocus_client.models.item_bulk_update import ItemBulkUpdate as ItemBulkUpdate
from airfocus_client.models.item_color import ItemColor as ItemColor
from airfocus_client.models.item_comment import ItemComment as ItemComment
from airfocus_client.models.item_comment_reaction import ItemCommentReaction as ItemCommentReaction
from airfocus_client.models.item_comment_search_query import ItemCommentSearchQuery as ItemCommentSearchQuery
from airfocus_client.models.item_comment_with_item_comment_embed import ItemCommentWithItemCommentEmbed as ItemCommentWithItemCommentEmbed
from airfocus_client.models.item_comment_with_item_comment_embed_page import ItemCommentWithItemCommentEmbedPage as ItemCommentWithItemCommentEmbedPage
from airfocus_client.models.item_constraint import ItemConstraint as ItemConstraint
from airfocus_client.models.item_constraint_integration_push_forbidden import ItemConstraintIntegrationPushForbidden as ItemConstraintIntegrationPushForbidden
from airfocus_client.models.item_constraint_integration_to_internal import ItemConstraintIntegrationToInternal as ItemConstraintIntegrationToInternal
from airfocus_client.models.item_constraint_property_read_only import ItemConstraintPropertyReadOnly as ItemConstraintPropertyReadOnly
from airfocus_client.models.item_constraint_undeletable import ItemConstraintUndeletable as ItemConstraintUndeletable
from airfocus_client.models.item_embed import ItemEmbed as ItemEmbed
from airfocus_client.models.item_embed_app import ItemEmbedApp as ItemEmbedApp
from airfocus_client.models.item_embed_integration import ItemEmbedIntegration as ItemEmbedIntegration
from airfocus_client.models.item_embed_progress import ItemEmbedProgress as ItemEmbedProgress
from airfocus_client.models.item_link_bulk_action import ItemLinkBulkAction as ItemLinkBulkAction
from airfocus_client.models.item_link_bulk_create import ItemLinkBulkCreate as ItemLinkBulkCreate
from airfocus_client.models.item_link_bulk_delete import ItemLinkBulkDelete as ItemLinkBulkDelete
from airfocus_client.models.item_link_bulk_patch import ItemLinkBulkPatch as ItemLinkBulkPatch
from airfocus_client.models.item_link_bulk_update import ItemLinkBulkUpdate as ItemLinkBulkUpdate
from airfocus_client.models.item_link_constraint_undeletable import ItemLinkConstraintUndeletable as ItemLinkConstraintUndeletable
from airfocus_client.models.item_link_embed import ItemLinkEmbed as ItemLinkEmbed
from airfocus_client.models.item_link_embed_app import ItemLinkEmbedApp as ItemLinkEmbedApp
from airfocus_client.models.item_link_search_query import ItemLinkSearchQuery as ItemLinkSearchQuery
from airfocus_client.models.item_link_type import ItemLinkType as ItemLinkType
from airfocus_client.models.item_link_with_item_link_embed import ItemLinkWithItemLinkEmbed as ItemLinkWithItemLinkEmbed
from airfocus_client.models.item_link_with_item_link_embed_page import ItemLinkWithItemLinkEmbedPage as ItemLinkWithItemLinkEmbedPage
from airfocus_client.models.item_relation_bulk_action import ItemRelationBulkAction as ItemRelationBulkAction
from airfocus_client.models.item_relation_bulk_create import ItemRelationBulkCreate as ItemRelationBulkCreate
from airfocus_client.models.item_relation_bulk_delete import ItemRelationBulkDelete as ItemRelationBulkDelete
from airfocus_client.models.item_relation_bulk_patch import ItemRelationBulkPatch as ItemRelationBulkPatch
from airfocus_client.models.item_relation_bulk_update import ItemRelationBulkUpdate as ItemRelationBulkUpdate
from airfocus_client.models.item_relation_create_request import ItemRelationCreateRequest as ItemRelationCreateRequest
from airfocus_client.models.item_relation_search_query import ItemRelationSearchQuery as ItemRelationSearchQuery
from airfocus_client.models.item_relation_search_query_filter import ItemRelationSearchQueryFilter as ItemRelationSearchQueryFilter
from airfocus_client.models.item_relation_search_query_filter_child import ItemRelationSearchQueryFilterChild as ItemRelationSearchQueryFilterChild
from airfocus_client.models.item_relation_search_query_filter_parent import ItemRelationSearchQueryFilterParent as ItemRelationSearchQueryFilterParent
from airfocus_client.models.item_relation_search_query_filter_parent_or_child import ItemRelationSearchQueryFilterParentOrChild as ItemRelationSearchQueryFilterParentOrChild
from airfocus_client.models.item_relation_update_request import ItemRelationUpdateRequest as ItemRelationUpdateRequest
from airfocus_client.models.item_relation_with_embed import ItemRelationWithEmbed as ItemRelationWithEmbed
from airfocus_client.models.item_relation_with_embed_page import ItemRelationWithEmbedPage as ItemRelationWithEmbedPage
from airfocus_client.models.item_search_query import ItemSearchQuery as ItemSearchQuery
from airfocus_client.models.item_search_query_date_time_filter_value import ItemSearchQueryDateTimeFilterValue as ItemSearchQueryDateTimeFilterValue
from airfocus_client.models.item_search_query_filter import ItemSearchQueryFilter as ItemSearchQueryFilter
from airfocus_client.models.item_search_query_filter_and import ItemSearchQueryFilterAnd as ItemSearchQueryFilterAnd
from airfocus_client.models.item_search_query_filter_assignees import ItemSearchQueryFilterAssignees as ItemSearchQueryFilterAssignees
from airfocus_client.models.item_search_query_filter_assignees_contain import ItemSearchQueryFilterAssigneesContain as ItemSearchQueryFilterAssigneesContain
from airfocus_client.models.item_search_query_filter_assignees_contains_all import ItemSearchQueryFilterAssigneesContainsAll as ItemSearchQueryFilterAssigneesContainsAll
from airfocus_client.models.item_search_query_filter_assignees_contains_any import ItemSearchQueryFilterAssigneesContainsAny as ItemSearchQueryFilterAssigneesContainsAny
from airfocus_client.models.item_search_query_filter_created_at import ItemSearchQueryFilterCreatedAt as ItemSearchQueryFilterCreatedAt
from airfocus_client.models.item_search_query_filter_field_value import ItemSearchQueryFilterFieldValue as ItemSearchQueryFilterFieldValue
from airfocus_client.models.item_search_query_filter_integration import ItemSearchQueryFilterIntegration as ItemSearchQueryFilterIntegration
from airfocus_client.models.item_search_query_filter_integration_value import ItemSearchQueryFilterIntegrationValue as ItemSearchQueryFilterIntegrationValue
from airfocus_client.models.item_search_query_filter_last_updated_at import ItemSearchQueryFilterLastUpdatedAt as ItemSearchQueryFilterLastUpdatedAt
from airfocus_client.models.item_search_query_filter_name import ItemSearchQueryFilterName as ItemSearchQueryFilterName
from airfocus_client.models.item_search_query_filter_name_contain import ItemSearchQueryFilterNameContain as ItemSearchQueryFilterNameContain
from airfocus_client.models.item_search_query_filter_name_equal import ItemSearchQueryFilterNameEqual as ItemSearchQueryFilterNameEqual
from airfocus_client.models.item_search_query_filter_not import ItemSearchQueryFilterNot as ItemSearchQueryFilterNot
from airfocus_client.models.item_search_query_filter_or import ItemSearchQueryFilterOr as ItemSearchQueryFilterOr
from airfocus_client.models.item_search_query_filter_parent import ItemSearchQueryFilterParent as ItemSearchQueryFilterParent
from airfocus_client.models.item_search_query_filter_parent_value import ItemSearchQueryFilterParentValue as ItemSearchQueryFilterParentValue
from airfocus_client.models.item_search_query_filter_status import ItemSearchQueryFilterStatus as ItemSearchQueryFilterStatus
from airfocus_client.models.item_search_query_filter_status_category import ItemSearchQueryFilterStatusCategory as ItemSearchQueryFilterStatusCategory
from airfocus_client.models.item_search_query_filter_status_category_contains_any import ItemSearchQueryFilterStatusCategoryContainsAny as ItemSearchQueryFilterStatusCategoryContainsAny
from airfocus_client.models.item_search_query_filter_status_category_updated_since import ItemSearchQueryFilterStatusCategoryUpdatedSince as ItemSearchQueryFilterStatusCategoryUpdatedSince
from airfocus_client.models.item_search_query_filter_status_contains_any import ItemSearchQueryFilterStatusContainsAny as ItemSearchQueryFilterStatusContainsAny
from airfocus_client.models.item_search_query_filter_status_updated_since import ItemSearchQueryFilterStatusUpdatedSince as ItemSearchQueryFilterStatusUpdatedSince
from airfocus_client.models.item_search_query_filter_updated_since import ItemSearchQueryFilterUpdatedSince as ItemSearchQueryFilterUpdatedSince
from airfocus_client.models.item_search_query_sort import ItemSearchQuerySort as ItemSearchQuerySort
from airfocus_client.models.item_search_query_sort_created_at import ItemSearchQuerySortCreatedAt as ItemSearchQuerySortCreatedAt
from airfocus_client.models.item_search_query_sort_direction import ItemSearchQuerySortDirection as ItemSearchQuerySortDirection
from airfocus_client.models.item_search_query_sort_field import ItemSearchQuerySortField as ItemSearchQuerySortField
from airfocus_client.models.item_search_query_sort_last_updated_at import ItemSearchQuerySortLastUpdatedAt as ItemSearchQuerySortLastUpdatedAt
from airfocus_client.models.item_search_query_sort_name import ItemSearchQuerySortName as ItemSearchQuerySortName
from airfocus_client.models.item_search_query_sort_order import ItemSearchQuerySortOrder as ItemSearchQuerySortOrder
from airfocus_client.models.item_search_query_sort_status import ItemSearchQuerySortStatus as ItemSearchQuerySortStatus
from airfocus_client.models.item_search_query_time_anchor import ItemSearchQueryTimeAnchor as ItemSearchQueryTimeAnchor
from airfocus_client.models.item_search_query_time_anchor_days import ItemSearchQueryTimeAnchorDays as ItemSearchQueryTimeAnchorDays
from airfocus_client.models.item_search_query_time_anchor_months import ItemSearchQueryTimeAnchorMonths as ItemSearchQueryTimeAnchorMonths
from airfocus_client.models.item_search_query_time_anchor_weeks import ItemSearchQueryTimeAnchorWeeks as ItemSearchQueryTimeAnchorWeeks
from airfocus_client.models.item_search_query_time_mode import ItemSearchQueryTimeMode as ItemSearchQueryTimeMode
from airfocus_client.models.item_type import ItemType as ItemType
from airfocus_client.models.item_with_item_embed import ItemWithItemEmbed as ItemWithItemEmbed
from airfocus_client.models.item_with_item_embed_page import ItemWithItemEmbedPage as ItemWithItemEmbedPage
from airfocus_client.models.item_with_md_with_item_embed import ItemWithMDWithItemEmbed as ItemWithMDWithItemEmbed
from airfocus_client.models.item_with_md_with_item_embed_page import ItemWithMDWithItemEmbedPage as ItemWithMDWithItemEmbedPage
from airfocus_client.models.json_patch_add import JsonPatchAdd as JsonPatchAdd
from airfocus_client.models.json_patch_copy import JsonPatchCopy as JsonPatchCopy
from airfocus_client.models.json_patch_move import JsonPatchMove as JsonPatchMove
from airfocus_client.models.json_patch_operation import JsonPatchOperation as JsonPatchOperation
from airfocus_client.models.json_patch_remove import JsonPatchRemove as JsonPatchRemove
from airfocus_client.models.json_patch_replace import JsonPatchReplace as JsonPatchReplace
from airfocus_client.models.json_patch_test import JsonPatchTest as JsonPatchTest
from airfocus_client.models.kick_user_request import KickUserRequest as KickUserRequest
from airfocus_client.models.milestone_bulk_action import MilestoneBulkAction as MilestoneBulkAction
from airfocus_client.models.milestone_bulk_create import MilestoneBulkCreate as MilestoneBulkCreate
from airfocus_client.models.milestone_bulk_delete import MilestoneBulkDelete as MilestoneBulkDelete
from airfocus_client.models.milestone_bulk_patch import MilestoneBulkPatch as MilestoneBulkPatch
from airfocus_client.models.milestone_bulk_update import MilestoneBulkUpdate as MilestoneBulkUpdate
from airfocus_client.models.milestone_with_embed import MilestoneWithEmbed as MilestoneWithEmbed
from airfocus_client.models.milestone_with_embed_page import MilestoneWithEmbedPage as MilestoneWithEmbedPage
from airfocus_client.models.mirror_source_field_with_field_embed import MirrorSourceFieldWithFieldEmbed as MirrorSourceFieldWithFieldEmbed
from airfocus_client.models.mirror_target_field_with_field_embed import MirrorTargetFieldWithFieldEmbed as MirrorTargetFieldWithFieldEmbed
from airfocus_client.models.number_field_type_settings import NumberFieldTypeSettings as NumberFieldTypeSettings
from airfocus_client.models.number_field_type_settings_stepping import NumberFieldTypeSettingsStepping as NumberFieldTypeSettingsStepping
from airfocus_client.models.number_field_type_settings_stepping_equal import NumberFieldTypeSettingsSteppingEqual as NumberFieldTypeSettingsSteppingEqual
from airfocus_client.models.number_field_type_settings_stepping_exponential import NumberFieldTypeSettingsSteppingExponential as NumberFieldTypeSettingsSteppingExponential
from airfocus_client.models.number_field_type_settings_unit import NumberFieldTypeSettingsUnit as NumberFieldTypeSettingsUnit
from airfocus_client.models.number_field_type_settings_unit_custom import NumberFieldTypeSettingsUnitCustom as NumberFieldTypeSettingsUnitCustom
from airfocus_client.models.number_field_type_settings_unit_money import NumberFieldTypeSettingsUnitMoney as NumberFieldTypeSettingsUnitMoney
from airfocus_client.models.number_field_with_field_embed import NumberFieldWithFieldEmbed as NumberFieldWithFieldEmbed
from airfocus_client.models.okr_checkins_field_with_field_embed import OkrCheckinsFieldWithFieldEmbed as OkrCheckinsFieldWithFieldEmbed
from airfocus_client.models.okr_confidence_field_settings import OkrConfidenceFieldSettings as OkrConfidenceFieldSettings
from airfocus_client.models.okr_confidence_field_with_field_embed import OkrConfidenceFieldWithFieldEmbed as OkrConfidenceFieldWithFieldEmbed
from airfocus_client.models.okr_key_result_reference_field_with_field_embed import OkrKeyResultReferenceFieldWithFieldEmbed as OkrKeyResultReferenceFieldWithFieldEmbed
from airfocus_client.models.okr_key_results_field_with_field_embed import OkrKeyResultsFieldWithFieldEmbed as OkrKeyResultsFieldWithFieldEmbed
from airfocus_client.models.okr_progress_field_with_field_embed import OkrProgressFieldWithFieldEmbed as OkrProgressFieldWithFieldEmbed
from airfocus_client.models.okr_time_period_field_settings import OkrTimePeriodFieldSettings as OkrTimePeriodFieldSettings
from airfocus_client.models.okr_time_period_field_with_field_embed import OkrTimePeriodFieldWithFieldEmbed as OkrTimePeriodFieldWithFieldEmbed
from airfocus_client.models.people_field_type_settings import PeopleFieldTypeSettings as PeopleFieldTypeSettings
from airfocus_client.models.people_field_with_field_embed import PeopleFieldWithFieldEmbed as PeopleFieldWithFieldEmbed
from airfocus_client.models.permission import Permission as Permission
from airfocus_client.models.portal_field_with_field_embed import PortalFieldWithFieldEmbed as PortalFieldWithFieldEmbed
from airfocus_client.models.prioritization_field_with_field_embed import PrioritizationFieldWithFieldEmbed as PrioritizationFieldWithFieldEmbed
from airfocus_client.models.ref_item_property import RefItemProperty as RefItemProperty
from airfocus_client.models.relative_item_info import RelativeItemInfo as RelativeItemInfo
from airfocus_client.models.resend_user_invite_request import ResendUserInviteRequest as ResendUserInviteRequest
from airfocus_client.models.rich_text import RichText as RichText
from airfocus_client.models.rich_text_block import RichTextBlock as RichTextBlock
from airfocus_client.models.rich_text_block_attachment import RichTextBlockAttachment as RichTextBlockAttachment
from airfocus_client.models.rich_text_block_blockquote import RichTextBlockBlockquote as RichTextBlockBlockquote
from airfocus_client.models.rich_text_block_code import RichTextBlockCode as RichTextBlockCode
from airfocus_client.models.rich_text_block_custom import RichTextBlockCustom as RichTextBlockCustom
from airfocus_client.models.rich_text_block_embed import RichTextBlockEmbed as RichTextBlockEmbed
from airfocus_client.models.rich_text_block_headline import RichTextBlockHeadline as RichTextBlockHeadline
from airfocus_client.models.rich_text_block_indentation import RichTextBlockIndentation as RichTextBlockIndentation
from airfocus_client.models.rich_text_block_list import RichTextBlockList as RichTextBlockList
from airfocus_client.models.rich_text_block_panel import RichTextBlockPanel as RichTextBlockPanel
from airfocus_client.models.rich_text_block_paragraph import RichTextBlockParagraph as RichTextBlockParagraph
from airfocus_client.models.rich_text_inline import RichTextInline as RichTextInline
from airfocus_client.models.rich_text_inline_bold import RichTextInlineBold as RichTextInlineBold
from airfocus_client.models.rich_text_inline_code import RichTextInlineCode as RichTextInlineCode
from airfocus_client.models.rich_text_inline_custom import RichTextInlineCustom as RichTextInlineCustom
from airfocus_client.models.rich_text_inline_image import RichTextInlineImage as RichTextInlineImage
from airfocus_client.models.rich_text_inline_italic import RichTextInlineItalic as RichTextInlineItalic
from airfocus_client.models.rich_text_inline_link import RichTextInlineLink as RichTextInlineLink
from airfocus_client.models.rich_text_inline_mention import RichTextInlineMention as RichTextInlineMention
from airfocus_client.models.rich_text_inline_strike_through import RichTextInlineStrikeThrough as RichTextInlineStrikeThrough
from airfocus_client.models.rich_text_inline_text import RichTextInlineText as RichTextInlineText
from airfocus_client.models.rich_text_inline_underline import RichTextInlineUnderline as RichTextInlineUnderline
from airfocus_client.models.rich_text_list_item import RichTextListItem as RichTextListItem
from airfocus_client.models.role import Role as Role
from airfocus_client.models.select_field_option_color import SelectFieldOptionColor as SelectFieldOptionColor
from airfocus_client.models.select_field_type_option import SelectFieldTypeOption as SelectFieldTypeOption
from airfocus_client.models.select_field_type_settings import SelectFieldTypeSettings as SelectFieldTypeSettings
from airfocus_client.models.select_field_with_field_embed import SelectFieldWithFieldEmbed as SelectFieldWithFieldEmbed
from airfocus_client.models.set_client_settings_request import SetClientSettingsRequest as SetClientSettingsRequest
from airfocus_client.models.set_workspace_statuses_request import SetWorkspaceStatusesRequest as SetWorkspaceStatusesRequest
from airfocus_client.models.status import Status as Status
from airfocus_client.models.status_category import StatusCategory as StatusCategory
from airfocus_client.models.status_color import StatusColor as StatusColor
from airfocus_client.models.store_accepted_tos_request import StoreAcceptedTosRequest as StoreAcceptedTosRequest
from airfocus_client.models.team import Team as Team
from airfocus_client.models.team_company_info import TeamCompanyInfo as TeamCompanyInfo
from airfocus_client.models.team_company_info_role import TeamCompanyInfoRole as TeamCompanyInfoRole
from airfocus_client.models.team_company_info_size import TeamCompanyInfoSize as TeamCompanyInfoSize
from airfocus_client.models.team_flag import TeamFlag as TeamFlag
from airfocus_client.models.team_flags import TeamFlags as TeamFlags
from airfocus_client.models.team_state import TeamState as TeamState
from airfocus_client.models.team_state_all_team_state_seats import TeamStateAllTeamStateSeats as TeamStateAllTeamStateSeats
from airfocus_client.models.team_state_seats import TeamStateSeats as TeamStateSeats
from airfocus_client.models.team_state_subscription import TeamStateSubscription as TeamStateSubscription
from airfocus_client.models.team_state_subscription_expired import TeamStateSubscriptionExpired as TeamStateSubscriptionExpired
from airfocus_client.models.team_state_subscription_trial import TeamStateSubscriptionTrial as TeamStateSubscriptionTrial
from airfocus_client.models.team_state_workspaces import TeamStateWorkspaces as TeamStateWorkspaces
from airfocus_client.models.template import Template as Template
from airfocus_client.models.template_app import TemplateApp as TemplateApp
from airfocus_client.models.template_category import TemplateCategory as TemplateCategory
from airfocus_client.models.template_page_with_embed import TemplatePageWithEmbed as TemplatePageWithEmbed
from airfocus_client.models.template_parameters import TemplateParameters as TemplateParameters
from airfocus_client.models.template_search_embed import TemplateSearchEmbed as TemplateSearchEmbed
from airfocus_client.models.template_view import TemplateView as TemplateView
from airfocus_client.models.text_field_with_field_embed import TextFieldWithFieldEmbed as TextFieldWithFieldEmbed
from airfocus_client.models.time_period import TimePeriod as TimePeriod
from airfocus_client.models.time_period_field_settings import TimePeriodFieldSettings as TimePeriodFieldSettings
from airfocus_client.models.time_period_field_settings_iterations import TimePeriodFieldSettingsIterations as TimePeriodFieldSettingsIterations
from airfocus_client.models.time_period_field_settings_simple import TimePeriodFieldSettingsSimple as TimePeriodFieldSettingsSimple
from airfocus_client.models.time_period_field_with_field_embed import TimePeriodFieldWithFieldEmbed as TimePeriodFieldWithFieldEmbed
from airfocus_client.models.update_item_link_request import UpdateItemLinkRequest as UpdateItemLinkRequest
from airfocus_client.models.update_item_request import UpdateItemRequest as UpdateItemRequest
from airfocus_client.models.update_item_request_with_md import UpdateItemRequestWithMD as UpdateItemRequestWithMD
from airfocus_client.models.update_milestone_request import UpdateMilestoneRequest as UpdateMilestoneRequest
from airfocus_client.models.update_team_flags_request import UpdateTeamFlagsRequest as UpdateTeamFlagsRequest
from airfocus_client.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from airfocus_client.models.update_workspace_request import UpdateWorkspaceRequest as UpdateWorkspaceRequest
from airfocus_client.models.user import User as User
from airfocus_client.models.user_ref import UserRef as UserRef
from airfocus_client.models.user_ref_user_ref_id import UserRefUserRefId as UserRefUserRefId
from airfocus_client.models.user_state import UserState as UserState
from airfocus_client.models.view import View as View
from airfocus_client.models.votes_field_with_field_embed import VotesFieldWithFieldEmbed as VotesFieldWithFieldEmbed
from airfocus_client.models.voting_app_score_field_type_settings import VotingAppScoreFieldTypeSettings as VotingAppScoreFieldTypeSettings
from airfocus_client.models.voting_score_field_with_field_embed import VotingScoreFieldWithFieldEmbed as VotingScoreFieldWithFieldEmbed
from airfocus_client.models.workspace import Workspace as Workspace
from airfocus_client.models.workspace_bulk_action import WorkspaceBulkAction as WorkspaceBulkAction
from airfocus_client.models.workspace_bulk_create import WorkspaceBulkCreate as WorkspaceBulkCreate
from airfocus_client.models.workspace_bulk_delete import WorkspaceBulkDelete as WorkspaceBulkDelete
from airfocus_client.models.workspace_bulk_patch import WorkspaceBulkPatch as WorkspaceBulkPatch
from airfocus_client.models.workspace_bulk_update import WorkspaceBulkUpdate as WorkspaceBulkUpdate
from airfocus_client.models.workspace_duplicate_request import WorkspaceDuplicateRequest as WorkspaceDuplicateRequest
from airfocus_client.models.workspace_embed import WorkspaceEmbed as WorkspaceEmbed
from airfocus_client.models.workspace_embed_relation import WorkspaceEmbedRelation as WorkspaceEmbedRelation
from airfocus_client.models.workspace_embed_workspace_group import WorkspaceEmbedWorkspaceGroup as WorkspaceEmbedWorkspaceGroup
from airfocus_client.models.workspace_group import WorkspaceGroup as WorkspaceGroup
from airfocus_client.models.workspace_group_assign_workspace_request import WorkspaceGroupAssignWorkspaceRequest as WorkspaceGroupAssignWorkspaceRequest
from airfocus_client.models.workspace_group_bulk_action import WorkspaceGroupBulkAction as WorkspaceGroupBulkAction
from airfocus_client.models.workspace_group_bulk_create import WorkspaceGroupBulkCreate as WorkspaceGroupBulkCreate
from airfocus_client.models.workspace_group_bulk_delete import WorkspaceGroupBulkDelete as WorkspaceGroupBulkDelete
from airfocus_client.models.workspace_group_bulk_patch import WorkspaceGroupBulkPatch as WorkspaceGroupBulkPatch
from airfocus_client.models.workspace_group_bulk_update import WorkspaceGroupBulkUpdate as WorkspaceGroupBulkUpdate
from airfocus_client.models.workspace_group_embed import WorkspaceGroupEmbed as WorkspaceGroupEmbed
from airfocus_client.models.workspace_group_permissions_update_request import WorkspaceGroupPermissionsUpdateRequest as WorkspaceGroupPermissionsUpdateRequest
from airfocus_client.models.workspace_group_search_embed import WorkspaceGroupSearchEmbed as WorkspaceGroupSearchEmbed
from airfocus_client.models.workspace_group_with_workspace_group_embed import WorkspaceGroupWithWorkspaceGroupEmbed as WorkspaceGroupWithWorkspaceGroupEmbed
from airfocus_client.models.workspace_group_with_workspace_group_search_embed import WorkspaceGroupWithWorkspaceGroupSearchEmbed as WorkspaceGroupWithWorkspaceGroupSearchEmbed
from airfocus_client.models.workspace_group_with_workspace_group_search_embed_page import WorkspaceGroupWithWorkspaceGroupSearchEmbedPage as WorkspaceGroupWithWorkspaceGroupSearchEmbedPage
from airfocus_client.models.workspace_namespace import WorkspaceNamespace as WorkspaceNamespace
from airfocus_client.models.workspace_permissions_update_request import WorkspacePermissionsUpdateRequest as WorkspacePermissionsUpdateRequest
from airfocus_client.models.workspace_progress_mode import WorkspaceProgressMode as WorkspaceProgressMode
from airfocus_client.models.workspace_relation import WorkspaceRelation as WorkspaceRelation
from airfocus_client.models.workspace_relation_bulk_action import WorkspaceRelationBulkAction as WorkspaceRelationBulkAction
from airfocus_client.models.workspace_relation_bulk_create import WorkspaceRelationBulkCreate as WorkspaceRelationBulkCreate
from airfocus_client.models.workspace_relation_bulk_delete import WorkspaceRelationBulkDelete as WorkspaceRelationBulkDelete
from airfocus_client.models.workspace_relation_bulk_patch import WorkspaceRelationBulkPatch as WorkspaceRelationBulkPatch
from airfocus_client.models.workspace_relation_bulk_update import WorkspaceRelationBulkUpdate as WorkspaceRelationBulkUpdate
from airfocus_client.models.workspace_relation_search_query import WorkspaceRelationSearchQuery as WorkspaceRelationSearchQuery
from airfocus_client.models.workspace_relation_search_query_filter import WorkspaceRelationSearchQueryFilter as WorkspaceRelationSearchQueryFilter
from airfocus_client.models.workspace_relation_search_query_filter_and import WorkspaceRelationSearchQueryFilterAnd as WorkspaceRelationSearchQueryFilterAnd
from airfocus_client.models.workspace_relation_search_query_filter_child import WorkspaceRelationSearchQueryFilterChild as WorkspaceRelationSearchQueryFilterChild
from airfocus_client.models.workspace_relation_search_query_filter_child_contain_any import WorkspaceRelationSearchQueryFilterChildContainAny as WorkspaceRelationSearchQueryFilterChildContainAny
from airfocus_client.models.workspace_relation_search_query_filter_child_equal import WorkspaceRelationSearchQueryFilterChildEqual as WorkspaceRelationSearchQueryFilterChildEqual
from airfocus_client.models.workspace_relation_search_query_filter_not import WorkspaceRelationSearchQueryFilterNot as WorkspaceRelationSearchQueryFilterNot
from airfocus_client.models.workspace_relation_search_query_filter_or import WorkspaceRelationSearchQueryFilterOr as WorkspaceRelationSearchQueryFilterOr
from airfocus_client.models.workspace_relation_search_query_filter_parent import WorkspaceRelationSearchQueryFilterParent as WorkspaceRelationSearchQueryFilterParent
from airfocus_client.models.workspace_relation_search_query_filter_parent_contain_any import WorkspaceRelationSearchQueryFilterParentContainAny as WorkspaceRelationSearchQueryFilterParentContainAny
from airfocus_client.models.workspace_relation_search_query_filter_parent_equal import WorkspaceRelationSearchQueryFilterParentEqual as WorkspaceRelationSearchQueryFilterParentEqual
from airfocus_client.models.workspace_relation_with_embed import WorkspaceRelationWithEmbed as WorkspaceRelationWithEmbed
from airfocus_client.models.workspace_relation_with_embed_page import WorkspaceRelationWithEmbedPage as WorkspaceRelationWithEmbedPage
from airfocus_client.models.workspace_relations_set_request import WorkspaceRelationsSetRequest as WorkspaceRelationsSetRequest
from airfocus_client.models.workspace_search_embed import WorkspaceSearchEmbed as WorkspaceSearchEmbed
from airfocus_client.models.workspace_search_query import WorkspaceSearchQuery as WorkspaceSearchQuery
from airfocus_client.models.workspace_search_query_filter import WorkspaceSearchQueryFilter as WorkspaceSearchQueryFilter
from airfocus_client.models.workspace_search_query_filter_and import WorkspaceSearchQueryFilterAnd as WorkspaceSearchQueryFilterAnd
from airfocus_client.models.workspace_search_query_filter_members_contain_any import WorkspaceSearchQueryFilterMembersContainAny as WorkspaceSearchQueryFilterMembersContainAny
from airfocus_client.models.workspace_search_query_filter_name import WorkspaceSearchQueryFilterName as WorkspaceSearchQueryFilterName
from airfocus_client.models.workspace_search_query_filter_name_contain import WorkspaceSearchQueryFilterNameContain as WorkspaceSearchQueryFilterNameContain
from airfocus_client.models.workspace_search_query_filter_name_equal import WorkspaceSearchQueryFilterNameEqual as WorkspaceSearchQueryFilterNameEqual
from airfocus_client.models.workspace_search_query_filter_namespace_contain_any import WorkspaceSearchQueryFilterNamespaceContainAny as WorkspaceSearchQueryFilterNamespaceContainAny
from airfocus_client.models.workspace_search_query_filter_not import WorkspaceSearchQueryFilterNot as WorkspaceSearchQueryFilterNot
from airfocus_client.models.workspace_search_query_filter_or import WorkspaceSearchQueryFilterOr as WorkspaceSearchQueryFilterOr
from airfocus_client.models.workspace_search_query_sort import WorkspaceSearchQuerySort as WorkspaceSearchQuerySort
from airfocus_client.models.workspace_search_query_sort_created_at import WorkspaceSearchQuerySortCreatedAt as WorkspaceSearchQuerySortCreatedAt
from airfocus_client.models.workspace_search_query_sort_direction import WorkspaceSearchQuerySortDirection as WorkspaceSearchQuerySortDirection
from airfocus_client.models.workspace_search_query_sort_last_updated_at import WorkspaceSearchQuerySortLastUpdatedAt as WorkspaceSearchQuerySortLastUpdatedAt
from airfocus_client.models.workspace_search_query_sort_name import WorkspaceSearchQuerySortName as WorkspaceSearchQuerySortName
from airfocus_client.models.workspace_with_workspace_embed import WorkspaceWithWorkspaceEmbed as WorkspaceWithWorkspaceEmbed
from airfocus_client.models.workspace_with_workspace_search_embed import WorkspaceWithWorkspaceSearchEmbed as WorkspaceWithWorkspaceSearchEmbed
from airfocus_client.models.workspace_with_workspace_search_embed_page import WorkspaceWithWorkspaceSearchEmbedPage as WorkspaceWithWorkspaceSearchEmbedPage
from airfocus_client.models.workspace_workspace_metadata import WorkspaceWorkspaceMetadata as WorkspaceWorkspaceMetadata
